### ISSUE TITLE
Update authors in DESCRIPTION

### ISSUE THREAD

**Issue by wlandau** [wlandau/workers#12]
CC @krlmlr.

**Comment by krlmlr** [comment]
Closed in e7bf137e7. No idea why it hasn't closed automatically.

**Comment by wlandau** [comment]
I think we were still on the `rstudio2019` branch at the time.

Thanks for a great couple coding sessions today! Like I said, I learn so much from you.

**Comment by krlmlr** [comment]
Thanks! I enjoyed it a lot, let's make _workers_ ready for production!
